name: Notify Ads Bot

on:
    schedule:
        - cron: "*/5 * * * *"
    workflow_dispatch:

jobs:
    notify_ads:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install requests apscheduler python-telegram-bot

            - name: Run the script
              env:
                  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
                  CHAT_ID: ${{ secrets.CHAT_ID }}
                  API_URL: ${{ secrets.API_URL }}
              run: python notify_ads.py
